### ISSUE TITLE
Another implementation in C

### ISSUE THREAD

**Issue by losfair** [alanzchen/rm-protection#4]
I've re-implemented `rm-protection` in the C programming language, which is available at https://github.com/losfair/rm-protection-c .

I would appreciate it if you would add it to `README.md`.

**Comment by alanzchen** [comment]
Hi,

Thanks for porting! I'm more than happy add this to `README.md`.

Just one thing, I hope you can keep the version number (also the behavior and features) as close to `rm-protection` as possible in the future.

And please remove "Known issues" from your `README.md` it has been resolved both in `rm-protection` and `rm-protection-c`.

Thanks again for your contribution.
