### ISSUE TITLE
Python 3.5 Import Error

### ISSUE THREAD

**Issue by sergeyshevch** [alanzchen/rm-protection#5]
Hello, Alan!

After installation on Fedora 25, Python 3.5, I met next trouble.
`Traceback (most recent call last):
  File "/bin/protect", line 7, in <module>
    from rm_protection.protect import protect
  File "/usr/lib/python3.5/site-packages/rm_protection/protect.py", line 5, in <module>
    from config import Config
ImportError: No module named 'config'
`
I fixed it by changing:
`from config import Config`
to:
`from .config import Config`

Is it my local problem or bug in the app?

P.s: I installed rm-protection globally on my system

**Comment by alanzchen** [comment]
Hi,

Thanks for the bug report! It seems that different Python versions handle the import statement differently. Now I have made the import statement explicit. My fault.

Now the latest commit should fix this issue, and you can install it again from PyPi.

**Comment by sergeyshevch** [comment]
Thanks
