### ISSUE TITLE
关于rm 显示 answer 的文件路径

### ISSUE THREAD

**Issue by fujinzhou** [alanzchen/rm-protection#8]
[lisi@localhost ~]$ rm /tmp/yum.log 
/tmp/yum.log: aey
Answer: s
Wrong answer! /tmp/yum.log will not be removed
The answer is stored in /tmp/.yum.log.rm-protection
rm: missing operand
Try `rm --help' for more information.

 建议把 answer 的文件路径注释掉

**Comment by alanzchen** [comment]
为什么如此建议？

**Comment by fujinzhou** [comment]
显示出answer的路径，那岂不是和没设置问题一样？操作的用户看到answer的答案还是可以删除，没起到限制删除的作用

**Comment by alanzchen** [comment]
`rm-protection` 的初衷是提醒用户防止误删，而不是「限制」或者「禁止」删除的作用。若是希望严格地禁止用户删除，请使用权限的方式实现。

提供文件信息是方便用户查看正确答案以获得关于文件内容的提示。实际上即便不提供，用户也知道 `.rm-protection` 的文件地址。

当然您可以在自己的系统上部署去除了提示的版本，但是在有足够多的人支持之前，我不会在 merge PR。

**Comment by fujinzhou** [comment]
嗯嗯。你的考虑也是有道理的
